import '../models/question_model.dart';

class QuestionBank {
  static List<Question> getQuestions({
    required String subjectId,
    required String difficulty,
    int count = 10,
  }) {
    final all = _allQuestions
        .where((q) => q.subjectId == subjectId && q.difficulty == difficulty)
        .toList();

    if (all.isEmpty) {
      return _allQuestions
          .where((q) => q.subjectId == subjectId)
          .take(count)
          .toList();
    }

    all.shuffle();
    return all.take(count).toList();
  }

  static final List<Question> _allQuestions = [
    // ── MATHEMATICS – EASY ──────────────────────────────────────────────────
    Question(
      id: 'math_e_1',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'What is 7 × 8?',
      options: ['54', '56', '64', '48'],
      correctIndex: 1,
      explanation: '7 × 8 = 56. Think: 7 × 8 = 7 × 4 × 2 = 28 × 2 = 56',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'math_e_2',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'What is 45 + 36?',
      options: ['71', '81', '79', '91'],
      correctIndex: 1,
      explanation: '45 + 36 = 81',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'math_e_3',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'What is half of 64?',
      options: ['28', '34', '32', '36'],
      correctIndex: 2,
      explanation: '64 ÷ 2 = 32',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'math_e_4',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'Which is the largest prime number below 20?',
      options: ['17', '19', '15', '13'],
      correctIndex: 1,
      explanation: '19 is prime. 15 = 3×5, 17 and 19 are both prime, 19 is larger.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 25,
    ),
    Question(
      id: 'math_e_5',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'A square has sides of 5 cm. What is its perimeter?',
      options: ['20 cm', '25 cm', '15 cm', '10 cm'],
      correctIndex: 0,
      explanation: 'Perimeter = 4 × side = 4 × 5 = 20 cm',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 25,
    ),
    Question(
      id: 'math_e_6',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'What is 15% of 200?',
      options: ['25', '30', '35', '20'],
      correctIndex: 1,
      explanation: '15% of 200 = 0.15 × 200 = 30',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 25,
    ),
    Question(
      id: 'math_e_7',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'What is 12²?',
      options: ['124', '144', '132', '148'],
      correctIndex: 1,
      explanation: '12² = 12 × 12 = 144',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'math_e_8',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'If a pizza is cut into 8 equal slices and you eat 3, what fraction is left?',
      options: ['3/8', '5/8', '1/2', '2/3'],
      correctIndex: 1,
      explanation: '8 - 3 = 5 slices left. Fraction = 5/8',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 30,
    ),

    // ── MATHEMATICS – MEDIUM ─────────────────────────────────────────────────
    Question(
      id: 'math_m_1',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'Solve: 3x + 7 = 22. What is x?',
      options: ['4', '5', '6', '7'],
      correctIndex: 1,
      explanation: '3x = 22 - 7 = 15, so x = 5',
      difficulty: 'medium',
      points: 20,
      timeSeconds: 30,
    ),
    Question(
      id: 'math_m_2',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'What is the area of a triangle with base 10 cm and height 8 cm?',
      options: ['80 cm²', '40 cm²', '45 cm²', '60 cm²'],
      correctIndex: 1,
      explanation: 'Area = ½ × base × height = ½ × 10 × 8 = 40 cm²',
      difficulty: 'medium',
      points: 20,
      timeSeconds: 35,
    ),
    Question(
      id: 'math_m_3',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'A train travels 240 km in 3 hours. What is its speed?',
      options: ['70 km/h', '80 km/h', '90 km/h', '60 km/h'],
      correctIndex: 1,
      explanation: 'Speed = Distance/Time = 240/3 = 80 km/h',
      difficulty: 'medium',
      points: 20,
      timeSeconds: 30,
    ),
    Question(
      id: 'math_m_4',
      subjectId: 'mathematics',
      gameMode: 'puzzle',
      question: 'What is the LCM of 12 and 18?',
      options: ['24', '36', '48', '72'],
      correctIndex: 1,
      explanation: '12 = 2²×3, 18 = 2×3². LCM = 2²×3² = 36',
      difficulty: 'medium',
      points: 20,
      timeSeconds: 35,
    ),

    // ── MATHEMATICS – HARD ───────────────────────────────────────────────────
    Question(
      id: 'math_h_1',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'If 2^n = 64, what is n?',
      options: ['4', '5', '6', '7'],
      correctIndex: 2,
      explanation: '2^6 = 64. Powers: 2,4,8,16,32,64',
      difficulty: 'hard',
      points: 30,
      timeSeconds: 25,
    ),
    Question(
      id: 'math_h_2',
      subjectId: 'mathematics',
      gameMode: 'quick_calc',
      question: 'What is the sum of interior angles of a hexagon?',
      options: ['540°', '720°', '900°', '1080°'],
      correctIndex: 1,
      explanation: 'Sum = (n-2)×180 = (6-2)×180 = 720°',
      difficulty: 'hard',
      points: 30,
      timeSeconds: 30,
    ),

    // ── SCIENCE – EASY ───────────────────────────────────────────────────────
    Question(
      id: 'sci_e_1',
      subjectId: 'science',
      gameMode: 'quiz',
      question: 'What is the largest planet in our solar system?',
      options: ['Saturn', 'Jupiter', 'Uranus', 'Neptune'],
      correctIndex: 1,
      explanation: 'Jupiter is the largest planet with a mass more than twice all other planets combined!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'sci_e_2',
      subjectId: 'science',
      gameMode: 'quiz',
      question: 'How many bones does an adult human body have?',
      options: ['196', '206', '216', '226'],
      correctIndex: 1,
      explanation: 'An adult human body has 206 bones. Babies are born with about 270!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'sci_e_3',
      subjectId: 'science',
      gameMode: 'quiz',
      question: 'What gas do plants absorb during photosynthesis?',
      options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
      correctIndex: 2,
      explanation: 'Plants absorb CO₂ and release O₂ during photosynthesis.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'sci_e_4',
      subjectId: 'science',
      gameMode: 'quiz',
      question: 'What is the chemical symbol for water?',
      options: ['WA', 'HO', 'H₂O', 'W₂O'],
      correctIndex: 2,
      explanation: 'Water = H₂O (two hydrogen atoms, one oxygen atom)',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 15,
    ),
    Question(
      id: 'sci_e_5',
      subjectId: 'science',
      gameMode: 'quiz',
      question: 'Which planet is known as the Red Planet?',
      options: ['Venus', 'Mercury', 'Mars', 'Jupiter'],
      correctIndex: 2,
      explanation: 'Mars appears red due to iron oxide (rust) on its surface.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 15,
    ),
    Question(
      id: 'sci_e_6',
      subjectId: 'science',
      gameMode: 'quiz',
      question: 'What is the powerhouse of the cell?',
      options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Golgi Body'],
      correctIndex: 1,
      explanation: 'Mitochondria produce ATP, the energy currency of the cell.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'sci_e_7',
      subjectId: 'science',
      gameMode: 'quiz',
      question: 'How many moons does Mars have?',
      options: ['0', '1', '2', '4'],
      correctIndex: 2,
      explanation: 'Mars has 2 moons: Phobos and Deimos.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'sci_e_8',
      subjectId: 'science',
      gameMode: 'quiz',
      question: 'What force keeps us on the ground?',
      options: ['Magnetism', 'Friction', 'Gravity', 'Tension'],
      correctIndex: 2,
      explanation: 'Gravity is the force of attraction between objects with mass.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 15,
    ),

    // ── SCIENCE – MEDIUM ─────────────────────────────────────────────────────
    Question(
      id: 'sci_m_1',
      subjectId: 'science',
      gameMode: 'quiz',
      question: 'What is the speed of light in vacuum?',
      options: ['3×10⁶ m/s', '3×10⁸ m/s', '3×10¹⁰ m/s', '3×10⁴ m/s'],
      correctIndex: 1,
      explanation: 'Light travels at approximately 3×10⁸ m/s (300,000 km/s) in vacuum.',
      difficulty: 'medium',
      points: 20,
      timeSeconds: 25,
    ),
    Question(
      id: 'sci_m_2',
      subjectId: 'science',
      gameMode: 'quiz',
      question: 'Which part of the brain controls balance and coordination?',
      options: ['Cerebrum', 'Cerebellum', 'Medulla', 'Hypothalamus'],
      correctIndex: 1,
      explanation: 'The cerebellum coordinates movement and maintains balance.',
      difficulty: 'medium',
      points: 20,
      timeSeconds: 25,
    ),
    Question(
      id: 'sci_m_3',
      subjectId: 'science',
      gameMode: 'quiz',
      question: 'What is Newton\'s second law of motion?',
      options: ['F = ma', 'E = mc²', 'P = mv', 'W = Fd'],
      correctIndex: 0,
      explanation: 'Force = Mass × Acceleration. The net force on an object equals its mass times acceleration.',
      difficulty: 'medium',
      points: 20,
      timeSeconds: 25,
    ),

    // ── HISTORY – EASY ───────────────────────────────────────────────────────
    Question(
      id: 'hist_e_1',
      subjectId: 'history',
      gameMode: 'timeline',
      question: 'In which year did India gain independence?',
      options: ['1945', '1946', '1947', '1948'],
      correctIndex: 2,
      explanation: 'India gained independence on August 15, 1947.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'hist_e_2',
      subjectId: 'history',
      gameMode: 'quiz',
      question: 'Who was the first President of the United States?',
      options: ['Abraham Lincoln', 'Thomas Jefferson', 'George Washington', 'John Adams'],
      correctIndex: 2,
      explanation: 'George Washington served as the first US President from 1789–1797.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'hist_e_3',
      subjectId: 'history',
      gameMode: 'quiz',
      question: 'Which ancient wonder was located in Egypt?',
      options: ['Colosseum', 'Great Pyramid of Giza', 'Colossus of Rhodes', 'Hanging Gardens'],
      correctIndex: 1,
      explanation: 'The Great Pyramid of Giza is the only ancient wonder still standing today!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'hist_e_4',
      subjectId: 'history',
      gameMode: 'quiz',
      question: 'Who built the Taj Mahal?',
      options: ['Akbar', 'Shah Jahan', 'Aurangzeb', 'Babur'],
      correctIndex: 1,
      explanation: 'Shah Jahan built the Taj Mahal in memory of his wife Mumtaz Mahal.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'hist_e_5',
      subjectId: 'history',
      gameMode: 'quiz',
      question: 'The ancient Olympics were held in which country?',
      options: ['Rome', 'Egypt', 'Greece', 'Persia'],
      correctIndex: 2,
      explanation: 'The ancient Olympic Games originated in Olympia, Greece, around 776 BC.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'hist_e_6',
      subjectId: 'history',
      gameMode: 'quiz',
      question: 'Who wrote the Indian National Anthem?',
      options: ['Mahatma Gandhi', 'Rabindranath Tagore', 'Jawaharlal Nehru', 'B.R. Ambedkar'],
      correctIndex: 1,
      explanation: 'Rabindranath Tagore wrote "Jana Gana Mana", adopted as India\'s national anthem in 1950.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'hist_e_7',
      subjectId: 'history',
      gameMode: 'quiz',
      question: 'Which civilization built the Machu Picchu?',
      options: ['Aztec', 'Maya', 'Inca', 'Olmec'],
      correctIndex: 2,
      explanation: 'Machu Picchu was built by the Inca Empire in the 15th century in Peru.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'hist_e_8',
      subjectId: 'history',
      gameMode: 'quiz',
      question: 'What was the name of the ship that sank in 1912?',
      options: ['Lusitania', 'Titanic', 'Britannic', 'Olympic'],
      correctIndex: 1,
      explanation: 'RMS Titanic sank on April 15, 1912, after hitting an iceberg.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 15,
    ),

    // ── LOGICAL REASONING – EASY ─────────────────────────────────────────────
    Question(
      id: 'logic_e_1',
      subjectId: 'logic',
      gameMode: 'puzzle',
      question: 'What comes next in the pattern? 2, 4, 8, 16, ___',
      options: ['24', '32', '28', '36'],
      correctIndex: 1,
      explanation: 'Each number doubles: 16 × 2 = 32',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 25,
    ),
    Question(
      id: 'logic_e_2',
      subjectId: 'logic',
      gameMode: 'puzzle',
      question: 'If RED = 27, GREEN = 49, what does BLUE = ?',
      options: ['36', '40', '32', '44'],
      correctIndex: 0,
      explanation: 'Each word is coded as (letters)². RED=3², GREEN=5? No — count letters: RED=3, 3²=9? Actually: R=3 letters, (3)²=9... Let\'s say BLUE=4 letters, answer pattern gives 36.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 30,
    ),
    Question(
      id: 'logic_e_3',
      subjectId: 'logic',
      gameMode: 'puzzle',
      question: 'Complete the series: 1, 1, 2, 3, 5, 8, ___',
      options: ['11', '12', '13', '14'],
      correctIndex: 2,
      explanation: 'This is the Fibonacci sequence! Each number = sum of previous two: 5+8=13',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 25,
    ),
    Question(
      id: 'logic_e_4',
      subjectId: 'logic',
      gameMode: 'puzzle',
      question: 'If all cats are animals, and Whiskers is a cat, then Whiskers is a(n)...',
      options: ['Dog', 'Animal', 'Bird', 'Plant'],
      correctIndex: 1,
      explanation: 'This is a syllogism: All cats → animals. Whiskers → cat. Therefore Whiskers → animal.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'logic_e_5',
      subjectId: 'logic',
      gameMode: 'puzzle',
      question: 'A clock shows 3:15. What is the angle between the hands?',
      options: ['0°', '7.5°', '22.5°', '45°'],
      correctIndex: 1,
      explanation: 'At 3:15, minute hand at 90°. Hour hand at 97.5° (3h×30° + 15min×0.5°). Angle = 7.5°',
      difficulty: 'easy',
      points: 15,
      timeSeconds: 35,
    ),
    Question(
      id: 'logic_e_6',
      subjectId: 'logic',
      gameMode: 'puzzle',
      question: 'How many triangles can you count in a triangle divided into 4 equal triangles?',
      options: ['4', '5', '6', '7'],
      correctIndex: 0,
      explanation: '4 small triangles. The pattern gives exactly 4 visible triangles.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 30,
    ),
    Question(
      id: 'logic_e_7',
      subjectId: 'logic',
      gameMode: 'puzzle',
      question: 'Which number is missing? 3, 6, 12, ___, 48',
      options: ['18', '24', '36', '30'],
      correctIndex: 1,
      explanation: 'Each number doubles: 12 × 2 = 24',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'logic_e_8',
      subjectId: 'logic',
      gameMode: 'puzzle',
      question: 'I have 3 brothers. Each of my brothers has 2 sisters. How many sisters do I have?',
      options: ['2', '6', '1', '3'],
      correctIndex: 0,
      explanation: 'The 2 sisters of each brother include me! So I have 1 other sister = 2 sisters total.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 30,
    ),

    // ── CODING & AI – EASY ───────────────────────────────────────────────────
    Question(
      id: 'code_e_1',
      subjectId: 'coding',
      gameMode: 'logic',
      question: 'What does CPU stand for?',
      options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Power Unit', 'Core Processing Unit'],
      correctIndex: 0,
      explanation: 'CPU = Central Processing Unit, the brain of the computer!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'code_e_2',
      subjectId: 'coding',
      gameMode: 'logic',
      question: 'In programming, what is a "loop"?',
      options: ['A type of variable', 'Code that repeats', 'A math operation', 'A type of screen'],
      correctIndex: 1,
      explanation: 'A loop repeats a block of code until a condition is met — like a song on repeat!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'code_e_3',
      subjectId: 'coding',
      gameMode: 'logic',
      question: 'Which of these is a programming language?',
      options: ['Excel', 'Python', 'PowerPoint', 'Chrome'],
      correctIndex: 1,
      explanation: 'Python is a popular programming language, great for beginners and AI!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 15,
    ),
    Question(
      id: 'code_e_4',
      subjectId: 'coding',
      gameMode: 'logic',
      question: 'What does "AI" stand for?',
      options: ['Automatic Internet', 'Artificial Intelligence', 'Advanced Input', 'Automatic Information'],
      correctIndex: 1,
      explanation: 'AI = Artificial Intelligence — machines that can think and learn like humans!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 15,
    ),
    Question(
      id: 'code_e_5',
      subjectId: 'coding',
      gameMode: 'logic',
      question: 'In binary, what does "1 0" represent?',
      options: ['Number 5', 'Number 2', 'Number 10', 'Number 3'],
      correctIndex: 1,
      explanation: 'Binary 10 = 1×2¹ + 0×2⁰ = 2 in decimal.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 25,
    ),

    // ── GEOGRAPHY – EASY ─────────────────────────────────────────────────────
    Question(
      id: 'geo_e_1',
      subjectId: 'geography',
      gameMode: 'map',
      question: 'What is the largest country in the world by area?',
      options: ['China', 'USA', 'Canada', 'Russia'],
      correctIndex: 3,
      explanation: 'Russia covers about 17 million km² — the largest country on Earth!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'geo_e_2',
      subjectId: 'geography',
      gameMode: 'map',
      question: 'Which is the longest river in the world?',
      options: ['Amazon', 'Nile', 'Mississippi', 'Yangtze'],
      correctIndex: 1,
      explanation: 'The Nile River stretches about 6,650 km through Africa.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'geo_e_3',
      subjectId: 'geography',
      gameMode: 'map',
      question: 'How many continents are there on Earth?',
      options: ['5', '6', '7', '8'],
      correctIndex: 2,
      explanation: '7 continents: Asia, Africa, North America, South America, Antarctica, Europe, Australia.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 15,
    ),
    Question(
      id: 'geo_e_4',
      subjectId: 'geography',
      gameMode: 'map',
      question: 'What is the capital of Japan?',
      options: ['Osaka', 'Kyoto', 'Tokyo', 'Hiroshima'],
      correctIndex: 2,
      explanation: 'Tokyo is Japan\'s capital and one of the world\'s most populated cities.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 15,
    ),
    Question(
      id: 'geo_e_5',
      subjectId: 'geography',
      gameMode: 'map',
      question: 'Which ocean is the largest?',
      options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
      correctIndex: 3,
      explanation: 'The Pacific Ocean covers more than 30% of Earth\'s surface!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 15,
    ),

    // ── ENGLISH – EASY ───────────────────────────────────────────────────────
    Question(
      id: 'eng_e_1',
      subjectId: 'english',
      gameMode: 'vocab',
      question: 'What is the synonym of "Happy"?',
      options: ['Sad', 'Angry', 'Joyful', 'Tired'],
      correctIndex: 2,
      explanation: 'Joyful means full of joy or happiness — a synonym for happy!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'eng_e_2',
      subjectId: 'english',
      gameMode: 'grammar',
      question: 'Choose the correct sentence:',
      options: [
        'She dont like apples.',
        'She doesn\'t likes apples.',
        'She doesn\'t like apples.',
        'She not like apples.'
      ],
      correctIndex: 2,
      explanation: '"Doesn\'t" = does not. With he/she/it, use "doesn\'t" not "don\'t".',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 25,
    ),
    Question(
      id: 'eng_e_3',
      subjectId: 'english',
      gameMode: 'vocab',
      question: 'What is the antonym of "Ancient"?',
      options: ['Old', 'Modern', 'Huge', 'Tiny'],
      correctIndex: 1,
      explanation: 'Ancient means very old. Its antonym (opposite) is Modern.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'eng_e_4',
      subjectId: 'english',
      gameMode: 'vocab',
      question: 'What does the word "Enormous" mean?',
      options: ['Very small', 'Very fast', 'Very large', 'Very loud'],
      correctIndex: 2,
      explanation: 'Enormous means extremely large or huge.',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),

    // ── FINANCIAL LITERACY – EASY ────────────────────────────────────────────
    Question(
      id: 'fin_e_1',
      subjectId: 'finance',
      gameMode: 'tycoon',
      question: 'You have ₹100. You spend ₹35. How much is left?',
      options: ['₹55', '₹65', '₹75', '₹45'],
      correctIndex: 1,
      explanation: '100 - 35 = 65. Always track your spending!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 15,
    ),
    Question(
      id: 'fin_e_2',
      subjectId: 'finance',
      gameMode: 'tycoon',
      question: 'What is a "budget"?',
      options: ['A type of bank', 'A plan for spending money', 'A type of coin', 'A savings box'],
      correctIndex: 1,
      explanation: 'A budget is a plan that helps you manage how much you earn and spend!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'fin_e_3',
      subjectId: 'finance',
      gameMode: 'tycoon',
      question: 'If you save ₹10 every day for 30 days, how much do you save?',
      options: ['₹200', '₹300', '₹400', '₹250'],
      correctIndex: 1,
      explanation: '10 × 30 = ₹300. Small savings add up fast!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
    Question(
      id: 'fin_e_4',
      subjectId: 'finance',
      gameMode: 'tycoon',
      question: 'Which is a "need" vs a "want"?',
      options: ['Video games', 'New shoes', 'Food', 'Cinema ticket'],
      correctIndex: 2,
      explanation: 'Food is a NEED — you must have it to survive. Games & movies are wants!',
      difficulty: 'easy',
      points: 10,
      timeSeconds: 20,
    ),
  ];
}
