import '../models/models.dart';

class QuestionService {
  static List<Question> get({required String subjectId, required String difficulty, int count=25, Set<String> exclude=const{}}) {
    var pool = _all.where((q)=>q.subjectId==subjectId&&q.difficulty==difficulty&&!exclude.contains(q.id)).toList();
    if (pool.isEmpty) pool = _all.where((q)=>q.subjectId==subjectId&&!exclude.contains(q.id)).toList();
    if (pool.isEmpty) pool = _all.where((q)=>q.subjectId==subjectId).toList();
    pool.shuffle();
    return pool.take(count).toList();
  }

  static List<String> allIds(String subjectId, String difficulty) =>
    _all.where((q)=>q.subjectId==subjectId&&q.difficulty==difficulty).map((q)=>q.id).toList();

  static Question _q(String id,String sub,String q,List<String> opts,int c,String exp,String diff) =>
    Question(id:id,subjectId:sub,question:q,options:opts,correctIndex:c,explanation:exp,difficulty:diff,
      points:diff=='easy'?10:diff=='medium'?20:30,timeSeconds:diff=='easy'?25:diff=='medium'?30:35);

  static final List<Question> _all = [
    // MATH EASY
    _q('me01','mathematics','What is 8 × 7?',['48','54','56','64'],2,'8×7=56','easy'),
    _q('me02','mathematics','What is 144 ÷ 12?',['10','11','12','13'],2,'144÷12=12','easy'),
    _q('me03','mathematics','What is 25% of 200?',['40','50','60','25'],1,'25%=¼, 200÷4=50','easy'),
    _q('me04','mathematics','Perimeter of a square with side 9 cm?',['27cm','36cm','18cm','45cm'],1,'P=4×9=36cm','easy'),
    _q('me05','mathematics','Smallest prime number?',['1','2','3','0'],1,'2 is the smallest prime (1 is NOT prime)','easy'),
    _q('me06','mathematics','What is ½ + ¼?',['¾','⅔','½','⅝'],0,'½+¼=2/4+1/4=3/4','easy'),
    _q('me07','mathematics','What is 60% of 150?',['80','90','70','100'],1,'0.6×150=90','easy'),
    _q('me08','mathematics','What is 13²?',['149','169','159','179'],1,'13×13=169','easy'),
    _q('me09','mathematics','Area of rectangle 8cm × 5cm?',['26cm²','40cm²','13cm²','30cm²'],1,'A=8×5=40cm²','easy'),
    _q('me10','mathematics','What is 1000 − 437?',['563','573','553','583'],0,'1000−437=563','easy'),
    _q('me11','mathematics','Degrees in a right angle?',['45°','180°','90°','360°'],2,'Right angle = 90°','easy'),
    _q('me12','mathematics','What is 3/4 as a decimal?',['0.34','0.75','0.43','0.25'],1,'3÷4=0.75','easy'),
    _q('me13','mathematics','Divisible by both 2 and 3?',['14','16','18','20'],2,'18÷2=9✓ 18÷3=6✓','easy'),
    _q('me14','mathematics','Value of 5! (5 factorial)?',['20','60','100','120'],3,'5!=5×4×3×2×1=120','easy'),
    _q('me15','mathematics','Round 4.768 to 1 decimal place.',['4.7','4.8','4.9','5.0'],1,'6≥5 so round up→4.8','easy'),
    _q('me16','mathematics','LCM of 4 and 6?',['12','24','8','6'],0,'LCM(4,6)=12','easy'),
    _q('me17','mathematics','HCF of 24 and 36?',['6','9','12','18'],2,'HCF(24,36)=12','easy'),
    _q('me18','mathematics','What is 2.5 × 4?',['8','9','10','12'],2,'2.5×4=10','easy'),
    _q('me19','mathematics','Third angle if two angles are 60° and 80°?',['30°','40°','50°','60°'],1,'180−60−80=40°','easy'),
    _q('me20','mathematics','What is √81?',['7','8','9','10'],2,'√81=9 (9×9=81)','easy'),
    _q('me21','mathematics','What is 15 × 15?',['215','225','235','245'],1,'15×15=225','easy'),
    _q('me22','mathematics','Which fraction is largest?',['½','⅓','¾','⅔'],2,'¾=0.75 is largest','easy'),
    _q('me23','mathematics','What is 20% of 500?',['50','75','100','80'],2,'0.20×500=100','easy'),
    _q('me24','mathematics','Sides of an octagon?',['6','7','8','9'],2,'Octa=8 in Greek','easy'),
    _q('me25','mathematics','What is 0.1 + 0.9?',['0.19','0.10','1.0','1.9'],2,'0.1+0.9=1.0','easy'),
    _q('me26','mathematics','What is 7³?',['343','314','371','337'],0,'7×7×7=343','easy'),
    _q('me27','mathematics','45 minutes as fraction of hour?',['¾','½','⅔','¼'],0,'45/60=3/4','easy'),
    _q('me28','mathematics','Next prime after 17?',['18','19','20','21'],1,'19 is prime','easy'),
    _q('me29','mathematics','Shirt ₹450 with 10% off. Sale price?',['₹395','₹400','₹405','₹415'],2,'450−45=₹405','easy'),
    _q('me30','mathematics','Roman numeral for 50?',['X','L','C','D'],1,'L=50 in Roman numerals','easy'),
    // MATH MEDIUM
    _q('mm01','mathematics','Solve: 4x − 5 = 11',['3','4','5','6'],1,'4x=16 → x=4','medium'),
    _q('mm02','mathematics','Speed of train 360km in 4 hours?',['80','90','100','110'],1,'360÷4=90 km/h','medium'),
    _q('mm03','mathematics','Area of circle radius 7cm (π=22/7)?',['154cm²','144cm²','176cm²','132cm²'],0,'πr²=22/7×49=154cm²','medium'),
    _q('mm04','mathematics','Simple interest ₹2000 at 5% for 3 years?',['₹200','₹250','₹300','₹350'],2,'SI=PRT/100=2000×5×3/100=₹300','medium'),
    _q('mm05','mathematics','2³ × 2⁴ = ?',['2⁶','2⁷','2¹²','2⁸'],1,'2^(3+4)=2⁷','medium'),
    _q('mm06','mathematics','Ratio boys:girls = 3:2 in class of 30. Boys?',['12','15','18','20'],2,'3/5×30=18','medium'),
    _q('mm07','mathematics','Slope of y = 3x + 2?',['2','3','5','1'],1,'In y=mx+c, slope m=3','medium'),
    _q('mm08','mathematics','Factorise: x² − 9',['(x+3)(x−3)','(x+9)(x−9)','(x+3)²','(x−3)²'],0,'Difference of squares','medium'),
    _q('mm09','mathematics','Hypotenuse of right triangle with legs 3 and 4?',['5','6','7','8'],0,'√(9+16)=√25=5','medium'),
    _q('mm10','mathematics','Median of: 3, 7, 1, 9, 5?',['5','6','7','3'],0,'Sorted: 1,3,5,7,9 → middle=5','medium'),
    _q('mm11','mathematics','Volume of cube side 5cm?',['75cm³','100cm³','125cm³','150cm³'],2,'5³=125cm³','medium'),
    _q('mm12','mathematics','Mean of 10,20,30,40,50?',['25','30','35','40'],1,'Sum=150÷5=30','medium'),
    _q('mm13','mathematics','Value of (-3)²?',['−9','9','6','−6'],1,'(−3)×(−3)=+9','medium'),
    _q('mm14','mathematics','Profit % buying ₹800 selling ₹1000?',['20%','25%','15%','30%'],1,'200/800×100=25%','medium'),
    _q('mm15','mathematics','Circumference of circle diameter 14cm (π=22/7)?',['44cm','88cm','22cm','66cm'],0,'C=πd=22/7×14=44cm','medium'),
    _q('mm16','mathematics','3 men build wall in 6 days. Men needed in 2 days?',['6','7','8','9'],3,'18 man-days÷2=9 men','medium'),
    _q('mm17','mathematics','√0.25 = ?',['0.05','0.5','0.025','5'],1,'0.5×0.5=0.25','medium'),
    _q('mm18','mathematics','40 students, 60% girls. Boys?',['14','16','18','20'],1,'Girls=24, Boys=16','medium'),
    _q('mm19','mathematics','Evaluate: 5² + 4² − 3²',['30','32','34','36'],1,'25+16−9=32','medium'),
    _q('mm20','mathematics','Angles of triangle: 45° and 75°. Third?',['50°','55°','60°','65°'],2,'180−45−75=60°','medium'),
    _q('mm21','mathematics','15% of 840?',['116','126','136','146'],1,'0.15×840=126','medium'),
    _q('mm22','mathematics','Solve: 2(x + 3) = 14',['3','4','5','6'],1,'2x+6=14 → x=4','medium'),
    _q('mm23','mathematics','Probability of picking blue from 3 red, 4 blue, 5 green?',['1/4','1/3','1/2','4/5'],1,'4/12=1/3','medium'),
    _q('mm24','mathematics','Compound interest formula is?',['P(1+R/100)^T−P','PRT/100','P+PRT/100','P×R×T'],0,'CI=P(1+R/100)^T−P','medium'),
    _q('mm25','mathematics','25% of 360?',['80','90','75','100'],1,'360÷4=90','medium'),
    // MATH HARD
    _q('mh01','mathematics','Solve: x² − 5x + 6 = 0',['x=1,6','x=2,3','x=−2,−3','x=3,4'],1,'(x−2)(x−3)=0','hard'),
    _q('mh02','mathematics','sin 30° = ?',['1','√3/2','1/2','√2/2'],2,'Standard value: sin30°=1/2','hard'),
    _q('mh03','mathematics','Sum of interior angles of 10-sided polygon?',['1440°','1260°','1080°','900°'],0,'(10−2)×180=1440°','hard'),
    _q('mh04','mathematics','If a²+b²=25 and ab=12, find (a+b)²',['48','49','50','51'],1,'a²+2ab+b²=25+24=49','hard'),
    _q('mh05','mathematics','log₁₀(1000) = ?',['2','3','4','10'],1,'log₁₀(10³)=3','hard'),
    _q('mh06','mathematics','Distance between (0,0) and (3,4)?',['5','6','7','√7'],0,'√(9+16)=5','hard'),
    _q('mh07','mathematics','cos 60° = ?',['1','√3/2','1/2','0'],2,'Standard: cos60°=1/2','hard'),
    _q('mh08','mathematics','Area of rhombus diagonals 12cm and 16cm?',['96cm²','192cm²','48cm²','64cm²'],0,'d₁×d₂/2=12×16/2=96','hard'),
    _q('mh09','mathematics','nth term of AP: 3,7,11,15,...?',['4n−1','4n+1','3n+1','n+3'],0,'a=3,d=4 → 3+(n−1)4=4n−1','hard'),
    _q('mh10','mathematics','Discriminant of 2x²−4x+2=0?',['0','4','8','16'],0,'b²−4ac=16−16=0','hard'),
    // SCIENCE EASY
    _q('se01','science','Gas plants absorb in photosynthesis?',['Oxygen','Carbon Dioxide','Nitrogen','Hydrogen'],1,'Plants absorb CO₂, release O₂','easy'),
    _q('se02','science','How many bones in adult human?',['196','206','216','186'],1,'206 bones in adults','easy'),
    _q('se03','science','Red Planet?',['Venus','Mars','Jupiter','Saturn'],1,'Mars is red due to iron oxide','easy'),
    _q('se04','science','H₂O is?',['Salt','Sugar','Water','Acid'],2,'H₂O = two hydrogen + one oxygen','easy'),
    _q('se05','science','Powerhouse of the cell?',['Nucleus','Ribosome','Mitochondria','Vacuole'],2,'Mitochondria produce ATP energy','easy'),
    _q('se06','science','Force keeping us on ground?',['Magnetic','Friction','Gravity','Buoyancy'],2,'Gravity pulls objects toward Earth','easy'),
    _q('se07','science','Largest planet?',['Saturn','Uranus','Neptune','Jupiter'],3,'Jupiter is the largest planet','easy'),
    _q('se08','science','Photosynthesis occurs in?',['Root','Stem','Leaf','Flower'],2,'Chloroplasts in leaves do photosynthesis','easy'),
    _q('se09','science','Animals that eat only plants?',['Carnivores','Omnivores','Herbivores','Decomposers'],2,'Herbivores eat only plants','easy'),
    _q('se10','science','Legs of an insect?',['4','6','8','10'],1,'All insects have 6 legs','easy'),
    _q('se11','science','Nearest star to Earth?',['Sirius','Alpha Centauri','Polaris','The Sun'],3,'The Sun is ~150 million km away','easy'),
    _q('se12','science','Vitamin from sunlight?',['Vitamin A','Vitamin B','Vitamin C','Vitamin D'],3,'Sunlight → Vitamin D','easy'),
    _q('se13','science','Sound travels fastest in?',['Air','Water','Vacuum','Solids'],3,'Fastest in solids','easy'),
    _q('se14','science','Unit of electric current?',['Volt','Watt','Ampere','Ohm'],2,'Current measured in Amperes','easy'),
    _q('se15','science','Most of Earth\'s atmosphere is?',['Oxygen','CO₂','Argon','Nitrogen'],3,'Nitrogen ~78% of atmosphere','easy'),
    _q('se16','science','Organ that pumps blood?',['Lungs','Liver','Kidney','Heart'],3,'Heart pumps blood around body','easy'),
    _q('se17','science','Liquid turning into gas is called?',['Condensation','Evaporation','Sublimation','Freezing'],1,'Evaporation = liquid → gas','easy'),
    _q('se18','science','Planet with rings?',['Mars','Jupiter','Saturn','Uranus'],2,'Saturn has the most famous rings','easy'),
    _q('se19','science','Chemical symbol for gold?',['Go','Gd','Au','Ag'],2,'Au from Latin "Aurum"','easy'),
    _q('se20','science','Chambers in human heart?',['2','3','4','5'],2,'4 chambers: 2 atria + 2 ventricles','easy'),
    _q('se21','science','Chemical formula of table salt?',['KCl','NaCl','MgCl₂','CaCl₂'],1,'NaCl = Sodium Chloride','easy'),
    _q('se22','science','SI unit of force?',['Joule','Watt','Newton','Pascal'],2,'Force in Newtons (N)','easy'),
    _q('se23','science','Planet closest to Sun?',['Venus','Earth','Mercury','Mars'],2,'Mercury is closest to the Sun','easy'),
    _q('se24','science','Caterpillar to butterfly is called?',['Evolution','Metamorphosis','Photosynthesis','Respiration'],1,'Metamorphosis = transformation in insects','easy'),
    _q('se25','science','Speed of light?',['3×10⁶ m/s','3×10⁸ m/s','3×10¹⁰ m/s','3×10⁴ m/s'],1,'~3×10⁸ m/s in vacuum','easy'),
    // SCIENCE MEDIUM
    _q('sm01','science','Newton\'s second law?',['F=mv','F=ma','F=mg','F=m/a'],1,'Force = Mass × Acceleration','medium'),
    _q('sm02','science','pH of pure water?',['5','6','7','8'],2,'Pure water has neutral pH = 7','medium'),
    _q('sm03','science','Brain part controlling balance?',['Cerebrum','Medulla','Cerebellum','Hypothalamus'],2,'Cerebellum controls balance','medium'),
    _q('sm04','science','Cell division is called?',['Meiosis','Mitosis','Osmosis','Diffusion'],1,'Mitosis produces 2 identical cells','medium'),
    _q('sm05','science','Atomic number of carbon?',['4','5','6','7'],2,'Carbon has 6 protons → atomic number 6','medium'),
    _q('sm06','science','Ohm\'s law: V = ?',['IR','I/R','I+R','I−R'],0,'V = I × R','medium'),
    _q('sm07','science','Lens used in magnifying glass?',['Concave','Convex','Plane','Bifocal'],1,'Convex (converging) lens magnifies','medium'),
    _q('sm08','science','Formula for density?',['Mass×Volume','Mass÷Volume','Volume÷Mass','Mass+Volume'],1,'Density = Mass ÷ Volume','medium'),
    _q('sm09','science','Who proposed evolution by natural selection?',['Newton','Einstein','Darwin','Mendel'],2,'Charles Darwin, 1859','medium'),
    _q('sm10','science','Chemical formula of CO₂?',['CO','CO₂','C₂O','C₂O₃'],1,'1 carbon + 2 oxygen atoms','medium'),
    _q('sm11','science','Force in circular motion?',['Gravitational','Centripetal','Frictional','Magnetic'],1,'Centripetal force acts toward center','medium'),
    _q('sm12','science','Function of white blood cells?',['Carry oxygen','Clot blood','Fight infection','Digest food'],2,'WBCs fight infections','medium'),
    _q('sm13','science','Sound cannot travel through?',['Water','Air','Vacuum','Wood'],2,'Sound needs a medium','medium'),
    _q('sm14','science','SI unit of power?',['Joule','Newton','Watt','Pascal'],2,'Power in Watts (W = J/s)','medium'),
    _q('sm15','science','Where is insulin produced?',['Liver','Kidney','Stomach','Pancreas'],3,'Pancreas produces insulin','medium'),
    _q('sm16','science','Plants lose water through leaves by?',['Transpiration','Evaporation','Respiration','Osmosis'],0,'Transpiration through stomata','medium'),
    _q('sm17','science','Vitamin for blood clotting?',['Vitamin A','Vitamin C','Vitamin D','Vitamin K'],3,'Vitamin K for clotting','medium'),
    _q('sm18','science','Boiling point of water at sea level?',['90°C','95°C','100°C','105°C'],2,'100°C at standard pressure','medium'),
    _q('sm19','science','Stick appears bent in water due to?',['Reflection','Refraction','Diffraction','Dispersion'],1,'Refraction bends light at water surface','medium'),
    _q('sm20','science','Human chromosomes pairs?',['22','23','24','46'],1,'23 pairs = 46 total','medium'),
    _q('sm21','science','Gas produced when acid reacts with metal?',['Oxygen','CO₂','Hydrogen','Nitrogen'],2,'Acid + Metal → Salt + H₂ gas','medium'),
    _q('sm22','science','Gas used in electric bulbs?',['Oxygen','Argon','CO₂','Hydrogen'],1,'Argon (inert) prevents filament burning','medium'),
    _q('sm23','science','What is pH of lemon juice (approximately)?',['2','4','7','10'],1,'Lemon juice is acidic ~pH 2-3','medium'),
    _q('sm24','science','Rock formed from magma?',['Sedimentary','Metamorphic','Igneous','Fossil'],2,'Igneous rock forms from cooled magma','medium'),
    _q('sm25','science','Process by which plants make food?',['Respiration','Digestion','Photosynthesis','Fermentation'],2,'CO₂+H₂O+sunlight → glucose+O₂','medium'),
    // HISTORY EASY
    _q('he01','history','India gained independence in?',['1945','1946','1947','1948'],2,'15 August 1947','easy'),
    _q('he02','history','Who built the Taj Mahal?',['Akbar','Humayun','Shah Jahan','Aurangzeb'],2,'Shah Jahan built it for Mumtaz Mahal','easy'),
    _q('he03','history','Who gave the slogan "Do or Die"?',['Nehru','Gandhi','Bose','Tilak'],1,'Gandhi during Quit India Movement 1942','easy'),
    _q('he04','history','First President of India?',['Nehru','Patel','Rajendra Prasad','Ambedkar'],2,'Dr Rajendra Prasad, 1950–1962','easy'),
    _q('he05','history','Columbus discovered America in?',['1392','1492','1592','1692'],1,'Christopher Columbus reached America in 1492','easy'),
    _q('he06','history','Ancient Olympics first held in?',['Rome','Persia','Egypt','Greece'],3,'Olympia, Greece, ~776 BC','easy'),
    _q('he07','history','Who wrote the Indian National Anthem?',['Gandhi','Tagore','Nehru','Ambedkar'],1,'Rabindranath Tagore wrote "Jana Gana Mana"','easy'),
    _q('he08','history','World War II ended in?',['1943','1944','1945','1946'],2,'WWII ended in 1945','easy'),
    _q('he09','history','First Prime Minister of India?',['Patel','Prasad','Nehru','Ambedkar'],2,'Jawaharlal Nehru, 1947–1964','easy'),
    _q('he10','history','First man to walk on the Moon?',['Yuri Gagarin','Buzz Aldrin','Neil Armstrong','John Glenn'],2,'Neil Armstrong, July 20, 1969','easy'),
    _q('he11','history','Indian Constitution came into force on?',['15 Aug 1947','26 Jan 1950','2 Oct 1950','14 Nov 1949'],1,'26 January 1950 — Republic Day','easy'),
    _q('he12','history','Who invented the telephone?',['Edison','Graham Bell','Tesla','Marconi'],1,'Alexander Graham Bell, 1876','easy'),
    _q('he13','history','Quit India Movement was in?',['1940','1941','1942','1943'],2,'8 August 1942','easy'),
    _q('he14','history','Great Wall of China protects from?',['Floods','Northern invaders','Earthquakes','Pirates'],1,'Built to protect from northern invaders','easy'),
    _q('he15','history','Battle of Plassey was in?',['1747','1757','1767','1777'],1,'Battle of Plassey, 1757','easy'),
    // HISTORY MEDIUM
    _q('hm01','history','Non-Cooperation Movement started in?',['1918','1920','1922','1924'],1,'Non-Cooperation Movement began in 1920','medium'),
    _q('hm02','history','Dandi March took place in?',['1928','1929','1930','1931'],2,'Gandhi\'s Salt March, March–April 1930','medium'),
    _q('hm03','history','Treaty that ended World War I?',['Treaty of Paris','Treaty of Rome','Treaty of Versailles','Treaty of Vienna'],2,'Treaty of Versailles, 1919','medium'),
    _q('hm04','history','French Revolution began in?',['1776','1789','1799','1804'],1,'French Revolution started 1789','medium'),
    _q('hm05','history','INC founded by?',['A.O. Hume','Tilak','Gandhi','Gokhale'],0,'Allan Octavian Hume founded INC in 1885','medium'),
    _q('hm06','history','UN founded in?',['1943','1944','1945','1946'],2,'UN founded October 24, 1945','medium'),
    _q('hm07','history','Arthashastra written by?',['Chandragupta','Ashoka','Chanakya','Bindusara'],2,'Chanakya (Kautilya) wrote Arthashastra','medium'),
    _q('hm08','history','Akbar\'s policy of religious tolerance?',['Deen-i-Ilahi','Sulh-i-kul','Jizyah','Zakat'],1,'Sulh-i-kul = peace with all','medium'),
    _q('hm09','history','First Governor-General of independent India?',['Rajagopalachari','Mountbatten','Nehru','Rajendra Prasad'],1,'Lord Mountbatten was first GG','medium'),
    _q('hm10','history','Magna Carta was signed in?',['1115','1215','1315','1415'],1,'Magna Carta signed 1215 in England','medium'),
    // LOGIC
    _q('le01','logic','Next: 2, 4, 8, 16, ___',['24','28','32','36'],2,'Doubles each time: 16×2=32','easy'),
    _q('le02','logic','Complete: 1,1,2,3,5,8,___',['11','12','13','14'],2,'Fibonacci: 5+8=13','easy'),
    _q('le03','logic','A taller than B, B taller than C. Shortest?',['A','B','C','Can\'t tell'],2,'A>B>C so C is shortest','easy'),
    _q('le04','logic','Next: A, C, E, G, ___',['H','I','J','K'],1,'Skip every other letter: I','easy'),
    _q('le05','logic','Monday=Day1, what day is Day6?',['Friday','Saturday','Thursday','Sunday'],1,'Mon=1,Tue=2,Wed=3,Thu=4,Fri=5,Sat=6','easy'),
    _q('le06','logic','Odd one out: 2,3,5,7,9,11',['3','7','9','11'],2,'9=3×3 is not prime','easy'),
    _q('le07','logic','Next: 100,90,81,73,___',['65','66','67','68'],1,'Differences:−10,−9,−8,−7 so 73−7=66','easy'),
    _q('le08','logic','Shape with no corners?',['Square','Triangle','Pentagon','Circle'],3,'Circle has no corners','easy'),
    _q('le09','logic','Which is missing: 3,6,12,___,48',['18','24','36','30'],1,'Doubles: 12×2=24','easy'),
    _q('le10','logic','All roses are flowers. Some flowers fade. Can all roses fade?',['Yes','No','Maybe','Always'],1,'Some≠all — logical fallacy','easy'),
    _q('lm01','logic','5 cats catch 5 mice in 5 mins. 100 mice in 100 mins needs how many cats?',['5','10','20','100'],0,'Same ratio: 5 cats','medium'),
    _q('lm02','logic','Next: 2,6,12,20,30,___',['40','42','44','46'],1,'Differences:4,6,8,10,12→30+12=42','medium'),
    _q('lm03','logic','Father is 4× son\'s age. Son is 10. Father\'s age when son is 20?',['45','50','55','60'],1,'Father=40 now, +10=50','medium'),
    _q('lm04','logic','Which number comes next: 1,4,9,16,25,___',['30','36','42','49'],1,'Perfect squares: 6²=36','medium'),
    _q('lm05','logic','If RED=27 using letter values (R=18,E=5,D=4), what is CAT?',['24','25','26','27'],0,'C=3,A=1,T=20=24','medium'),
    // CODING
    _q('ce01','coding','CPU stands for?',['Central Processing Unit','Computer Personal Unit','Central Power Unit','Core Processing Unit'],0,'CPU = Central Processing Unit','easy'),
    _q('ce02','coding','A "loop" in programming?',['A variable','Code that repeats','A math function','An error'],1,'Loop repeats code until condition met','easy'),
    _q('ce03','coding','HTML stands for?',['HyperText Markup Language','High Tech Modern Language','Hyper Transfer Medium Language','Home Tool Markup Language'],0,'HTML = HyperText Markup Language','easy'),
    _q('ce04','coding','AI stands for?',['Automatic Interface','Artificial Intelligence','Advanced Input','Automatic Information'],1,'AI = Artificial Intelligence','easy'),
    _q('ce05','coding','Binary "1010" = ?',['8','10','12','14'],1,'1×8+0×4+1×2+0×1=10','easy'),
    _q('ce06','coding','A "bug" in programming is?',['An insect','A feature','An error','A database'],2,'A bug is an error in code','easy'),
    _q('ce07','coding','CSS is used for?',['Logic','Styling web pages','Databases','Networking'],1,'CSS styles web pages','easy'),
    _q('ce08','coding','www stands for?',['World Wide Web','Wide World Web','World Web Wide','Web World Wide'],0,'www = World Wide Web','easy'),
    _q('ce09','coding','Ctrl+Z does what?',['Save','Copy','Undo','Paste'],2,'Ctrl+Z = Undo last action','easy'),
    _q('ce10','coding','Which is NOT a programming language?',['Python','HTML','Java','Photoshop'],3,'Photoshop is design software','easy'),
    _q('cm01','coding','"if-else" in programming?',['Loops code','Makes decisions','Stores data','Prints output'],1,'if-else = conditional decision making','medium'),
    _q('cm02','coding','An "algorithm" is?',['A computer type','Step-by-step problem-solving','A language','A virus'],1,'Algorithm = step-by-step instructions','medium'),
    _q('cm03','coding','RAM stands for?',['Random Access Memory','Read All Memory','Run All Modules','Rapid Array Module'],0,'RAM = Random Access Memory','medium'),
    _q('cm04','coding','Output of print(2**10) in Python?',['20','102','1024','512'],2,'2¹⁰=1024','medium'),
    _q('cm05','coding','AI that learns from data without explicit programming?',['Rule-based AI','Machine Learning','Expert System','Robotic AI'],1,'Machine Learning trains on data','medium'),
    // GEOGRAPHY
    _q('ge01','geography','Largest country by area?',['Canada','China','USA','Russia'],3,'Russia ~17.1 million km²','easy'),
    _q('ge02','geography','Longest river?',['Amazon','Yangtze','Mississippi','Nile'],3,'Nile ~6,650 km','easy'),
    _q('ge03','geography','Number of continents?',['5','6','7','8'],2,'7 continents','easy'),
    _q('ge04','geography','Capital of Japan?',['Osaka','Kyoto','Hiroshima','Tokyo'],3,'Tokyo is Japan\'s capital','easy'),
    _q('ge05','geography','Largest ocean?',['Atlantic','Indian','Arctic','Pacific'],3,'Pacific covers 30%+ of Earth','easy'),
    _q('ge06','geography','Capital of Australia?',['Sydney','Melbourne','Brisbane','Canberra'],3,'Canberra (not Sydney!)','easy'),
    _q('ge07','geography','Smallest country?',['Monaco','San Marino','Vatican City','Liechtenstein'],2,'Vatican City = 0.44 km²','easy'),
    _q('ge08','geography','Mount Everest is in?',['Alps','Andes','Rockies','Himalayas'],3,'Himalayas, Nepal/Tibet border','easy'),
    _q('ge09','geography','Capital of France?',['Lyon','Marseille','Paris','Nice'],2,'Paris is France\'s capital','easy'),
    _q('ge10','geography','Capital of India?',['Mumbai','Kolkata','Chennai','New Delhi'],3,'New Delhi is India\'s capital','easy'),
    _q('ge11','geography','Amazon River flows through?',['Africa','Asia','Europe','South America'],3,'Amazon flows through Brazil','easy'),
    _q('ge12','geography','Largest desert?',['Sahara','Gobi','Arabian','Antarctic'],3,'Antarctic Desert ~14.2 million km²','easy'),
    _q('ge13','geography','Currency of Japan?',['Yuan','Yen','Won','Ringgit'],1,'Japan\'s currency is Yen (¥)','easy'),
    _q('ge14','geography','Most populated country?',['USA','China','India','Russia'],1,'China (India close behind)','easy'),
    _q('ge15','geography','Country with most freshwater lakes?',['USA','Brazil','Canada','Russia'],2,'Canada has ~60% of world\'s lakes','easy'),
    _q('gm01','geography','Suez Canal separates?',['Asia & Europe','Africa & Asia','Africa & Europe','Europe & America'],1,'Africa (west) from Asia (east)','medium'),
    _q('gm02','geography','Capital of Brazil?',['Rio de Janeiro','São Paulo','Salvador','Brasília'],3,'Brasília since 1960','medium'),
    _q('gm03','geography','International Date Line follows which meridian?',['0°','90°E','180°','90°W'],2,'~180° meridian','medium'),
    _q('gm04','geography','Country with most time zones?',['USA','Russia','China','France'],3,'France (overseas territories) has 12','medium'),
    _q('gm05','geography','Tropic of Cancer passes through India?',['Only Rajasthan','Only Gujarat','Only MP','Multiple states'],3,'Gujarat, Rajasthan, MP and more','medium'),
    // ENGLISH
    _q('ee01','english','Synonym of "Happy"?',['Sad','Angry','Joyful','Tired'],2,'Joyful = full of happiness','easy'),
    _q('ee02','english','Antonym of "Ancient"?',['Old','Big','Modern','Slow'],2,'Ancient = very old, opposite = Modern','easy'),
    _q('ee03','english','"Enormous" means?',['Very small','Very fast','Very loud','Very large'],3,'Enormous = extremely large','easy'),
    _q('ee04','english','Correct sentence?',['She don\'t like apples.','She doesn\'t likes apples.','She doesn\'t like apples.','She not like apples.'],2,'Use "doesn\'t" with she/he/it','easy'),
    _q('ee05','english','Plural of "child"?',['Childs','Childes','Children','Childrens'],2,'Irregular plural = children','easy'),
    _q('ee06','english','Fill: It ___ raining outside.',['are','were','is','was'],2,'Current weather: "It is raining"','easy'),
    _q('ee07','english','Which word is a verb?',['Beautiful','Quickly','Run','Apple'],2,'Run is a verb (action word)','easy'),
    _q('ee08','english','Past tense of "go"?',['Goed','Gone','Went','Going'],2,'Irregular past: "went"','easy'),
    _q('ee09','english','Opposite of "victory"?',['Win','Success','Defeat','Triumph'],2,'Defeat is antonym of victory','easy'),
    _q('ee10','english','Superlative of "good"?',['Gooder','Better','Best','Most good'],2,'Best is superlative of good','easy'),
    _q('ee11','english','A "noun" is?',['Action word','Describing word','Connecting word','Person, place, or thing'],3,'Noun = person, place, thing, idea','easy'),
    _q('ee12','english','She ___ to school every day.',['go','goes','going','gone'],1,'Use "goes" with she/he/it','easy'),
    _q('ee13','english','Synonym of "brave"?',['Cowardly','Fearful','Courageous','Timid'],2,'Courageous = brave','easy'),
    _q('ee14','english','Passive voice: "She wrote a letter."',['She wrote a letter.','A letter was written by her.','She writes letters.','She is writing.'],1,'"Was written" = passive voice','easy'),
    _q('ee15','english','Which punctuation ends a question?',['Period','Comma','Question mark','Exclamation mark'],2,'Questions end with ?','easy'),
    _q('em01','english','A "metaphor" is?',['Comparing with "like"','Direct comparison without "like"','Exaggeration','Repeating sounds'],1,'Metaphor: one thing IS another','medium'),
    _q('em02','english','"The stars danced" is an example of?',['Simile','Metaphor','Personification','Hyperbole'],2,'Personification = human quality to non-human','medium'),
    _q('em03','english','Prefix "un-" means?',['Again','Together','Not/opposite','Before'],2,'"Un-" = not: unhappy, unkind','medium'),
    _q('em04','english','Correct punctuation?',['Lets eat grandma.','Let\'s eat grandma.','Let\'s eat, grandma.','Lets eat, grandma.'],2,'Comma after eat saves grandma!','medium'),
    _q('em05','english','An "oxymoron" is?',['Exaggeration','Contradiction in terms','List of items','Sound repetition'],1,'E.g., "deafening silence", "living dead"','medium'),
    // FINANCE
    _q('fe01','finance','₹200 − ₹85 = ?',['₹105','₹115','₹125','₹135'],1,'200−85=₹115','easy'),
    _q('fe02','finance','A "budget" is?',['A type of bank','A plan for managing money','A type of coin','A savings account'],1,'Budget = plan to track income and expenses','easy'),
    _q('fe03','finance','Save ₹10/day for 30 days?',['₹200','₹250','₹300','₹350'],2,'10×30=₹300','easy'),
    _q('fe04','finance','₹500 item at 20% discount. Price?',['₹380','₹390','₹400','₹410'],2,'500−100=₹400','easy'),
    _q('fe05','finance','Bank pays you for keeping money?',['Rent','Tax','Interest','Profit'],2,'Banks pay interest on savings','easy'),
    _q('fe06','finance','₹5000/month, save ₹1000. Savings rate?',['10%','15%','20%','25%'],2,'1000/5000×100=20%','easy'),
    _q('fe07','finance','What is "inflation"?',['Rising prices over time','Falling prices','A type of tax','A savings scheme'],0,'Inflation = general rise in price levels','easy'),
    _q('fe08','finance','GST stands for?',['General Sales Tax','Goods and Services Tax','Government Service Tariff','Gross Sales Total'],1,'GST = Goods and Services Tax','easy'),
    _q('fe09','finance','SI for ₹1000 at 10% for 2 years?',['₹100','₹150','₹200','₹250'],2,'SI=PRT/100=1000×10×2/100=₹200','easy'),
    _q('fe10','finance','A "need" not a "want"?',['Video games','Cinema ticket','Food','Toy'],2,'Food = need, games = want','easy'),
    _q('fm01','finance','Compound interest is?',['Interest on principal only','Interest on principal+past interest','Tax on income','Bank fee'],1,'CI earns interest on interest too','medium'),
    _q('fm02','finance','Profit % buying ₹1200, selling ₹1500?',['20%','25%','30%','15%'],1,'300/1200×100=25%','medium'),
    _q('fm03','finance','EMI stands for?',['Easy Money Installment','Equated Monthly Installment','Equal Money Income','Electronic Money Interface'],1,'EMI = Equated Monthly Installment','medium'),
    _q('fm04','finance','Car worth ₹5L loses 10% each year. Value after 2 years?',['₹4.00L','₹4.05L','₹4.10L','₹3.90L'],1,'5×0.9×0.9=4.05L','medium'),
    _q('fm05','finance','Stock market is where?',['Fruits sold','Company shares traded','Government bank','Insurance bought'],1,'Shares/stocks of companies bought and sold','medium'),
  ];
}
